### ISSUE TITLE
Phpstan latte 

### ISSUE THREAD

**Issue by lulco** [spaze/michalspacek.cz#139]
Hi, we are collecting interesting errors which phpstan-latte found in our applications. I want to ask you if there were some real bugs found or just some annoying errors which ment you have to rewrite your working app.

**Comment by spaze** [comment]
Hi, I don't remember any "real bug" as in "oh, this doesn't work but I haven't noticed". But I don't even remember any annoying errors that forced me to change otherwise perfect app 😅

What I like and am seeing (also with PHPStan itself) is that areas with some bad design are sort of highlighted. See, sometimes I think of PHPStan as a lamp illuminating areas you'd rather like to stay dark, sometimes very dark. These problematic areas tend to be the source of future problems because you probably didn't understand something when these parts were written, and frankly, sometimes you don't even understand them now. I consider those equally bad bugs. And this also applies to the PHPStan Latte extension.

Actually, these are very annoying because sometimes, when seeing some problems reported by the extension, I remember thinking "this should be done differently/better but I'm out if time and that's too much work to do it properly, who cares" 😁

**Comment by lulco** [comment]
OK thank you :) it just confirmed my feelings. On older apps all “real” bugs are already fixed because they are used for long time. Of course, bad design is highlighted as you said.

**Comment by spaze** [comment]
Yeah, some of the templates in this repo/site are 10+ years old and the site is rather small so "real" bugs are fixed rather quickly after they're introduced. I like one of the PHPStan's own claims "Find bugs before they reach production" so I'm trying to get the codebase to higher levels so that I can apply stricter checks and rules to the new code before it reaches prod :-) I know about the baseline feature but that would be the easy way... Thx!

**Comment by spaze** [comment]
I remembered you may be interested in this, when fixing errors on level 7, I found out I [had a form component and a form container sharing the same name](https://github.com/spaze/michalspacek.cz/pull/176/commits/9fda4ddb2edeb26d16540d4339be8824b5d78950). It worked but probably just by coincidence.
